import { randomBytes } from "node:crypto";

import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

import { SESSION_COOKIE_NAME, verifySession } from "@/lib/auth/session";

/**
 * Two independent jobs live in this one file, because Next.js only runs a single
 * proxy/middleware function per app: (1) `admin-authentication.md`'s NFR-3 ("no admin route
 * reachable without a valid TOTP-verified session") — T6.1's `admin_user`/`admin_session`
 * tables and T6.2's `/admin/setup-2fa` existed before this, but nothing actually checked a
 * session until now; and (2) issuing a per-request CSP nonce and the `Content-Security-
 * Policy` header itself (added session 62, once `kaalbert.com` was live to test against —
 * see `memory/technical-debt.md`'s now-resolved CSP entry), site-wide, not just on `/admin`.
 *
 * Next.js 16 renamed `middleware.ts` to `proxy.ts` (CLAUDE.md's Auth Pattern section) — a
 * stray `middleware.ts` here would be silently ignored at build time with no error, which
 * would make this whole file a no-op with nothing surfacing that fact. Runs on the Node.js
 * runtime by default (not Edge), so it can call `verifySession` — a real Prisma query —
 * directly, the same way any server-side code in this project does.
 *
 * **The matcher now covers every route** (excluding Next's own static/image-optimization
 * internals), not just `/admin`/`/api/admin` — broadened at session 62 specifically so the
 * CSP nonce/header applies to every public page too. The session-check logic below is still
 * scoped internally to `isAdminPath` — broadening the matcher must never broaden which paths
 * get the auth check, only which paths get a CSP header.
 *
 * Two path groups are deliberately excluded from the session check, both because they are
 * how a session gets created in the first place: the auth-flow pages themselves
 * (`/admin/login`, `/admin/setup-2fa`, and — added at T6.7 — `/admin/forgot-password`/
 * `/admin/reset-password`; each protected by its own mechanism, a password/TOTP form or a
 * single-use token, not a session) and every `/api/admin/auth/*` route (`login`,
 * `verify-totp`, T6.2's `setup-2fa` confirm, T6.4's `verify-backup-code`, and T6.7's
 * `request-password-reset`/`reset-password`) — a prefix check so a future auth endpoint
 * under that path doesn't need a second edit here to stay reachable.
 *
 * **Real bug hit and fixed at T6.7 (session 43)**: `/admin/forgot-password` and
 * `/admin/reset-password` were built without adding them to `PUBLIC_ADMIN_PAGE_PATHS` below
 * — both pages compiled, typechecked, and linted cleanly, but every unauthenticated visitor
 * (the only kind either page is ever reached by) was silently redirected straight back to
 * `/admin/login` before rendering. Caught only via live Playwright verification against the
 * real dev server, not by any static check — the same class of "compiles fine, never
 * actually reachable" failure `app/proxy.ts` vs. `proxy.ts` itself was at T6.3 (see
 * `memory/known-bugs.md`). Whenever a new unauthenticated `/admin/*` page is added, it must
 * be added to this set in the same change, not discovered missing later.
 */
export const config = {
  matcher: ["/((?!_next/static|_next/image|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico)$).*)"],
};

const PUBLIC_ADMIN_PAGE_PATHS = new Set([
  "/admin/login",
  "/admin/setup-2fa",
  "/admin/forgot-password",
  "/admin/reset-password",
]);

/**
 * `sendTransactionalEmail`/GTM's own bootstrap script is the project's one genuinely inline
 * `<script>` (`components/google-tag-manager.tsx`) — everything else Next.js itself injects
 * (framework chunks, the `self.__next_f.push(...)` hydration-payload scripts) is also inline
 * but is generated by Next.js's own renderer, not this project's code, so it can't carry a
 * hardcoded nonce prop. Next.js has a documented mechanism for exactly this: when a CSP
 * header containing a `nonce-` token is present on both the outgoing *request* headers (via
 * `NextResponse.next({ request: { headers } })`) and the response, the App Router's own
 * renderer automatically applies that same nonce to every script tag it generates itself —
 * no per-script code change needed on Next's side. `'strict-dynamic'` is what then lets
 * GTM's own nonce'd bootstrap script load its own further scripts (GA4's `gtag.js`, and any
 * future tag a partner adds via GTM's UI, per `docs/user-guide.md`'s documented "add a new
 * tag yourself" workflow) without those needing their own explicit host entries here —
 * browsers that support `strict-dynamic` ignore the `https:`/`'unsafe-inline'` fallback
 * tokens entirely; only pre-CSP3 browsers fall back to them. `connect-src`/`img-src`/
 * `frame-src` are NOT covered by `strict-dynamic` (it only governs script loading) — a
 * genuinely new third-party domain added via GTM later (not just a new event/trigger using
 * already-allowed domains) would still need a real edit here, a known, inherent CSP+GTM
 * limitation, not a bug.
 */
function buildContentSecurityPolicy(nonce: string): string {
  const r2Origin = process.env.CLOUDFLARE_R2_PUBLIC_URL;
  const imgSrc = [
    "'self'",
    "data:", // the admin 2FA setup screen's QR code (`qrcode` package) renders as a data: URI
    "https://www.googletagmanager.com",
    "https://www.google-analytics.com",
    ...(r2Origin ? [r2Origin] : []), // article/team-photo images — real R2 URLs, not data: (T7.2+)
  ];

  // React's dev-mode-only debug tooling (stack-trace reconstruction) calls eval(), which
  // production React explicitly never does ("React will never use eval() in production
  // mode" — its own console message). Scoping 'unsafe-eval' to non-production keeps local
  // dev console-clean without weakening the policy actually served to real visitors.
  const scriptSrc = [
    "'self'",
    `'nonce-${nonce}'`,
    "'strict-dynamic'",
    "'unsafe-inline'",
    "https:",
    ...(process.env.NODE_ENV !== "production" ? ["'unsafe-eval'"] : []),
  ];

  const directives = [
    "default-src 'self'",
    `script-src ${scriptSrc.join(" ")}`,
    "style-src 'self' 'unsafe-inline'", // React's dynamic `style={{...}}` attrs (progress bars) need this
    `img-src ${imgSrc.join(" ")}`,
    "font-src 'self'", // no Google Fonts/next/font in this project — system font stacks only
    "connect-src 'self' https://www.googletagmanager.com https://www.google-analytics.com https://analytics.google.com https://*.google-analytics.com https://*.analytics.google.com",
    "frame-src 'self' https://www.googletagmanager.com", // GTM's <noscript> iframe fallback
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'self'",
    "upgrade-insecure-requests",
  ];
  return directives.join("; ");
}

export async function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  const nonce = randomBytes(16).toString("base64");
  const csp = buildContentSecurityPolicy(nonce);

  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce", nonce);
  requestHeaders.set("Content-Security-Policy", csp);

  const isAdminPath = pathname.startsWith("/admin") || pathname.startsWith("/api/admin");

  if (!isAdminPath) {
    const response = NextResponse.next({ request: { headers: requestHeaders } });
    response.headers.set("Content-Security-Policy", csp);
    return response;
  }

  if (pathname.startsWith("/api/admin/auth/") || PUBLIC_ADMIN_PAGE_PATHS.has(pathname)) {
    const response = NextResponse.next({ request: { headers: requestHeaders } });
    response.headers.set("Content-Security-Policy", csp);
    return response;
  }

  const token = request.cookies.get(SESSION_COOKIE_NAME)?.value;
  const session = token ? await verifySession(token) : null;

  if (session) {
    const response = NextResponse.next({ request: { headers: requestHeaders } });
    response.headers.set("Content-Security-Policy", csp);
    return response;
  }

  if (pathname.startsWith("/api/admin/")) {
    const response = NextResponse.json(
      { status: "error", message: "Authentication required." },
      { status: 401 },
    );
    response.headers.set("Content-Security-Policy", csp);
    return response;
  }

  const response = NextResponse.redirect(new URL("/admin/login", request.url));
  response.headers.set("Content-Security-Policy", csp);
  return response;
}
