import type { Metadata } from "next";

import {
  GoogleTagManagerBodyFrame,
  GoogleTagManagerHeadScript,
} from "@/components/google-tag-manager";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Empty GTM container (ADR 0006) — no tags configured yet, see T1.6. Unset in dev/CI until
// a real container is provisioned (memory/technical-debt.md → "GTM container not yet
// provisioned"), so the snippet renders only once GTM_CONTAINER_ID is set.
const gtmContainerId = process.env.GTM_CONTAINER_ID;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      {gtmContainerId ? <GoogleTagManagerHeadScript containerId={gtmContainerId} /> : null}
      <body>
        {gtmContainerId ? <GoogleTagManagerBodyFrame containerId={gtmContainerId} /> : null}
        {children}
      </body>
    </html>
  );
}
