import type { Metadata } from "next";

import {
  GoogleTagManagerBodyFrame,
  GoogleTagManagerHeadScript,
} from "@/components/google-tag-manager";

import "./globals.css";

// A fallback only. A plain string here (not a `{ default, template }` object) means a child
// route's own `title` string fully replaces it rather than being interpolated into a
// template — correct for this codebase's convention of every page setting its own complete,
// firm-suffixed title (e.g. "Business Health Check — Kaalbert & Company Ltd") via
// generateMetadata; a template would double that suffix. This is what a visitor sees only if
// a route somehow forgets to set its own. Previously left at create-next-app's own default
// ("Create Next App"/"Generated by create next app"), which would have been visible on any
// such route on the live, deployed site.
export const metadata: Metadata = {
  title: "Kaalbert & Company Ltd — Business Advisory, Ghana",
  description:
    "Get your numbers, systems and plans into the shape banks, investors and boards expect. Take the free, six-minute Business Health Check.",
};

// Empty GTM container (ADR 0006) — no tags configured yet, see T1.6. Unset in dev/CI until
// a real container is provisioned (memory/technical-debt.md → "GTM container not yet
// provisioned"), so the snippet renders only once GTM_CONTAINER_ID is set.
const gtmContainerId = process.env.GTM_CONTAINER_ID;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      {gtmContainerId ? <GoogleTagManagerHeadScript containerId={gtmContainerId} /> : null}
      <body>
        {gtmContainerId ? <GoogleTagManagerBodyFrame containerId={gtmContainerId} /> : null}
        {children}
      </body>
    </html>
  );
}
