import type { Metadata } from "next";

import { ConsentBanner } from "@/components/consent-banner";
import {
  GoogleTagManagerBodyFrame,
  GoogleTagManagerHeadScript,
} from "@/components/google-tag-manager";

import "./globals.css";

// A fallback only. A plain string here (not a `{ default, template }` object) means a child
// route's own `title` string fully replaces it rather than being interpolated into a
// template — correct for this codebase's convention of every page setting its own complete,
// firm-suffixed title (e.g. "Business Health Check — Kaalbert & Company Ltd") via
// generateMetadata; a template would double that suffix. This is what a visitor sees only if
// a route somehow forgets to set its own. Previously left at create-next-app's own default
// ("Create Next App"/"Generated by create next app"), which would have been visible on any
// such route on the live, deployed site.
export const metadata: Metadata = {
  title: "Kaalbert & Company Ltd — Business Advisory, Ghana",
  description:
    "Get your numbers, systems and plans into the shape banks, investors and boards expect. Take the free, six-minute Business Health Check.",
};

// The real container (GTM-PDGKRKRN, provisioned T5.3, see memory/decision-log.md) — populated
// with the six conversion events, GA4 linkage, and consent mode (ADR 0006). Still read from
// the environment rather than hardcoded, and the snippet still renders nothing if unset
// (kept for local/CI environments without a real ID), consistent with the original T1.6 design.
const gtmContainerId = process.env.GTM_CONTAINER_ID;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      {gtmContainerId ? <GoogleTagManagerHeadScript containerId={gtmContainerId} /> : null}
      <body>
        {gtmContainerId ? <GoogleTagManagerBodyFrame containerId={gtmContainerId} /> : null}
        {children}
        <ConsentBanner />
      </body>
    </html>
  );
}
